### ISSUE TITLE
Website generator

### ISSUE THREAD

**Issue by sandstrom** [transmission/transmission.github.io#4]
How is your current website generated?

If you would like to I may be able to contribute a [Middleman website](https://middlemanapp.com/).

**Comment by JohnClay** [comment]
The website is generated through GitHub Pages; it's a live from this repo.

**Comment by sandstrom** [comment]
Alright, seems like you've got something good in place then!

I noticed you've put effort into a series of security improvements lately. That's awsome! ⛵
