### ISSUE TITLE
Windows download links are incorrect

### ISSUE THREAD

**Issue by XeonBionic** [transmission/transmission.github.io#48]
The download links for the windows versions link to https://github.com/transmission/transmission-releases/raw/master/Transmission-3.00-x64.msi instead of https://github.com/transmission/transmission/releases/download/3.00/transmission-3.00-x64.msi | /transmission/transmission/releases/download/3.00/*file here*  instead of /transmission/transmission-releases/raw/master/*file here* | This means that the windows download links on the website are invalid.

**Comment by JohJohan** [comment]
I can confirm i am seeing the same thing. But i checked the code and it looks okay: https://github.com/transmission/transmission.github.io/blob/master/download/index.html#L30 Maybe the production isn't running the master branch?

**Comment by XeonBionic** [comment]
> I can confirm i am seeing the same thing. But i checked the code and it looks okay: https://github.com/transmission/transmission.github.io/blob/master/download/index.html#L30 Maybe the production isn't running the master branch?

This is what looks like is happening. It's literally just a simple copy and paste of a different link in the HTML once or twice, which really isn't hard to fix at all.

**Comment by JohJohan** [comment]
@XeonBionic do you know where the incorrect link is? I dont see it in the code.

**Comment by XeonBionic** [comment]
> @XeonBionic do you know where the incorrect link is? I dont see it in the code.

Lines 109 & 111, download.html

**Comment by JohJohan** [comment]
@XeonBionic i see correct links: https://github.com/transmission/transmission.github.io/blob/master/download.html#L109 Also can confirm links on the site are workin correctly probably fixed with: https://github.com/transmission/transmission.github.io/commit/9294c80d16ec92f4b91902d41d12648dbbbc3b23.

Ticket can be closed.
