### ISSUE TITLE
please move "trim21/transmission-rpc" to addons "Remote control libraries"

### ISSUE THREAD

**Issue by trim21** [transmission/transmission.github.io#60]
Hi, I'm the maintainer of https://github.com/trim21/transmission-rpc, and I just find it's listed at [addons](https://transmissionbt.com/addons) page.

I believe it should be one of "Remote control libraries" instead of currently "Standalone remote controls"

**Comment by trim21** [comment]
@ckerr

**Comment by ckerr** [comment]
Hi @trim21! Thanks for the ping. Could you make a PR to make this correction?

**Comment by trim21** [comment]
@ckerr https://github.com/transmission/transmission.github.io/pull/86 please
