### ISSUE TITLE
Transmission Website refresh

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission.github.io#64]
It has been a significant amount of time since the Transmission website had a refresh. As one user put it today @shatteredsite 

> "Right now it needs a complete redesign and would do far more good with far fewer headaches or conflict. The site visually screams 'not maintained' and it has also been a while since a major release, compounding the issue further."

I couldn't agree more. I'm sticking my hand up to work on this if there are other fellow web professionals who would like to get involved.

**Comment by mikedld** [comment]
@microchip8, @Anton-Sagurov, @skynetpanda9, this issue 1) was misplaced to begin with and 2) is closed as completed. If you want changes made to the website, please open a new one (or better yet, a PR) here in [transmission/transmission.github.io](https://github.com/transmission/transmission.github.io). Thanks.

**Comment by CapeCrusader321** [comment]
I have recently published Snap Packages, it would have been good if it was added too.

**_1) Gtk Variant_**

<a href="https://snapcraft.io/transmission-community">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>

**_2) Qt Variant_**

<a href="https://snapcraft.io/transmission-snap-qt">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>

**Comment by klxq520** [comment]
When will Android phones be supported?

**Comment by anoteng** [comment]
The ubuntu ppa has unfortunately been long neglected, and I apologize for this. I have a bit more time again now, so I just updated it with the latest release. I'll continue keeping the latest release backported to all supported ubuntu releases. I'll look into reviving the beta and nightly builds later. If you'd like to re-add it to the download page the link is here: https://launchpad.net/~transmissionbt/+archive/ubuntu/ppa

**Comment by redpay** [comment]
In the Download tab I would like to request instructions to install Transmission on Fedora Atomic, the website currently says to use dnf for Fedora but the Atomic version of Fedora does not have dnf.

**Comment by jmallorquing** [comment]
Hi Team,
Thank you for the project, it could be possible to add Almalinux? I see that default Almalinux doesn't have the latest version of Transmission.
Thank you very much.
