### ISSUE TITLE
Website OpenBSD Logo Transparency

### ISSUE THREAD

**Issue by shatteredsite** [transmission/transmission.github.io#78]
### What is the issue?

The OpenBSD logo on the Transmission website has a white background rather than transparent. This shows on dark mode as a very ugly white square around the logo. If the logo has the white background made transparent, that will solve the issue.

### Which application of Transmission?

None

**Comment by mikedld** [comment]
Thanks, fixed in fe7742ff4a486fbce26f045695689f67efe0664d.
